name: Build Jellyfin CN

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动点一下运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 自动获取最新 Jellyfin 版本号
      - name: Get latest Jellyfin version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/jellyfin/jellyfin/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          echo "JELLYFIN_VERSION=$VERSION" >> $GITHUB_ENV

      # Docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录你的 Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 + 推两个标签：版本号 + latest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64  # 你是 x86_64 就用这个
          tags: |
            cavon/jellyfin:${{ env.JELLYFIN_VERSION }}
            cavon/jellyfin:latest
